### ISSUE TITLE
Treemap- SVG -Labels not fit in treemap blocks

### ISSUE THREAD

**Issue by Monali-ITT** [apache/incubator-echarts#10732]
### Version
4.2.1

### Reproduction link
[https://jsfiddle.net/5ogdkse6/3/](https://jsfiddle.net/5ogdkse6/3/)

### Steps to reproduce
1. Render echart in SVG.
2. The output is displayed correctly. But the labels in treemap blocks go out of blocks. Or overlapped another block.

### What is expected?
-With SVG, it should not overlap labels or should be fit in blocks.

### What is actually happening?
- Labels go out of blocks and overlap on another blocks.

**Comment by Monali-ITT** [comment]
Hi, @Ovilia  - is there any update. please let us know. We need it urgently.

**Comment by Ovilia** [comment]
@Monali-ITT I fixed it in https://github.com/ecomfe/zrender/pull/482 .
It will not be included in the next release since we are already testing the next release.
But you can build it by yourself. Here's how to build it:

```
cd xxx
git clone git@github.com:ecomfe/zrender.git
cd zrender
npm i

cd xxx (the same path)
git clone git@github.com:apache/incubator-echarts.git
cd incubator-echarts
npm i
node build/build.js --release
```

The built files are under `dist`.

**Comment by Monali-ITT** [comment]
Hi @Ovilia,
 I have checked with latest version 4.3.0.But the issue still reproducible.
Can you please please share working demo?

**Comment by Ovilia** [comment]
@Monali-ITT I will have a check.

**Comment by Monali-ITT** [comment]
@Ovilia,  Thank you for reply. It is not overlapping text in 4.4.0 version.

I have attached a screen shot.In that, labels are not display in some blocks.
How to display all labels in all blocks at the time of initial load?  
![treemap440](https://user-images.githubusercontent.com/52197143/67083861-8db1e300-f1b9-11e9-808b-617247fb7a01.png)

**Comment by Ovilia** [comment]
@pissang said that this is the expected result for both Canvas and SVG. Any comments?

**Comment by Monali-ITT** [comment]
@Ovilia , yes it shows labels on click of blocks. I want to download entire image(i.e initial state) as SVG or print the same image with all labels.How can I display all labels on downloaded image or print of that image?
please let me know.
