### ISSUE TITLE
tooltip.appendToBody scroll-issue on touch devices

### ISSUE THREAD

**Issue by tmtron** [apache/incubator-echarts#12776]
### Version
4.8.0

### Reproduction link
[https://stackblitz.com/edit/angular-echarts-append-to-body](https://stackblitz.com/edit/angular-echarts-append-to-body)

### Steps to reproduce

- Open the stackblitz example in Goolge Chrome.  
- Press the "Open in New Window" button at the right-top.
- Press F12 to open Developer Tools.
- Click the "Toggle Device Toolbar" icon at the left top of chrome tools - or press CTRL-SHIFT-M.
- Click on any bar to show the tooltip window.
- Scroll down: The tooltip will remain at it's position.

![2020-06-09_08h50_55](https://user-images.githubusercontent.com/20422904/84116361-f6431e00-aa2f-11ea-8a09-8ec362563ba8.gif)

### What is expected?
When some e-charts are in a scroll-container the tooltip should scroll (or maybe be hidden, if scroll is not possible)

### What is actually happening?
When some e-charts are in a scroll-container the tooltip will remain fixed (to the body)..

### Additional
On a real phone (using Goolge Chrome mobile), we see an additional issue (which may have the same cause).  
When we scroll down to the 2nd or 3rd echart and click a bar the tooltip will not show up (I guess that the calculated position is off the screen boundaries.

**Comment by wf123537200** [comment]
Is the issue the same as #12778 ?

**Comment by tmtron** [comment]
@Ovilia why the waiting-for:author tag: do you need some more info?

**Comment by ArturMiszkowicz** [comment]
This also persist in version 5.0.0.
As you can see on screenshot (anonymyzed) there are two tooltips, while mouse is between charts (during scroll). The tooltips will be there until user moves his mouse over chart to show another tooltip. 
![image](https://user-images.githubusercontent.com/63780672/101130411-b8e8d300-3603-11eb-85bd-990064c6883b.png)

**Comment by sunbin12121** [comment]
加 1

**Comment by pissang** [comment]
@tmtron It should be the same issue as #12778. Which has been fixed in 5.0
@ArturMiszkowicz I think it's a new issue brought in 5.0.0. It has been fixed since 5.0.1 https://github.com/apache/echarts/releases/tag/5.0.1

**Comment by tmtron** [comment]
@pissang I can still reproduce the issue in 5.0.1

Here is an updated [Stackblitz example](https://stackblitz.com/edit/angular-echarts-append-to-body-5?file=package.json)

**Comment by plainheart** [comment]
Yes, this issue seems to be there. I'm wondering how we should properly handle this case, hide or scroll?

**Comment by tmtron** [comment]
> Yes, this issue seems to be there. I'm wondering how we should properly handle this case, hide or scroll?

I could live with both - maybe it makes sense to add an option and let the users choose.

**Comment by Flourad** [comment]
移动端appendToBody开启后tooltip无法正常关闭的bug在最新版本里还是存在，请问什么时候可以解决

**Comment by tmtron** [comment]
+1

**Comment by programmingPug** [comment]
Still an issue, can we close the tooltip on scroll?

**Comment by programmingPug** [comment]
Actually found a solution with my own question, on the parent of the scrollable container have a listener for scroll then just call the method and dispatch the hide action. 

 public onScroll(event: Event): void {
    this.chart.dispatchAction({
      type: 'hideTip'
    });
  }

**Comment by xy1041** [comment]
Still an issue, any updates?

**Comment by ns-ujani** [comment]
+1
