### ISSUE TITLE
Time axis - bar chart start position moving out of x-axis

### ISSUE THREAD

**Issue by vij1ay** [apache/incubator-echarts#4862]
### One-line summary [问题简述]

When using Time Axis for bar chart, If the value available for the start position then it moves left to the x-start axis to keep bar position centered(same for end position or stacked bar). pl check the screenshots attached.

![device_vmnic0_at_01_00_0_bnx2](https://cloud.githubusercontent.com/assets/3069381/21643464/67313c6c-d2ae-11e6-8eb3-5166e7220be9.png)
![intel_r__pro_1000_mt_network_connection__2_symantec_endpoint_protection_firewall_0000](https://cloud.githubusercontent.com/assets/3069381/21643465/675fb7c2-d2ae-11e6-9183-489b3dabb5b9.png)

**Comment by 100pah** [comment]
I hope that [boundaryGap](https://ecomfe.github.io/echarts-doc/public/en/option.html#xAxis.boundaryGap) can help you ~

**Comment by akansal1** [comment]
This issue persits when axis is continous **```value```** or **```time```**, boundary gap is sufficient for end points, but this problems occurs again when we zoom inside

Example code from documentation has similar issue:

```option = {
    dataZoom: [
        {
            id: 'dataZoomX',
            type: 'slider',
            xAxisIndex: [0],
            filterMode: 'empty'
        },
        {
            id: 'dataZoomY',
            type: 'slider',
            yAxisIndex: [0],
            filterMode: 'empty'
        }
    ],
    xAxis: {type: 'value',nameLocation:'start'},
    yAxis: {type: 'value'},
    series:{
        type: 'bar',
        data: [
            // The first column corresponds to xAxis,
            // and the second coloum corresponds to yAxis.
            [12, 24, 36],
            [90, 80, 70],
            [3, 9, 27],
            [1, 11, 111]
        ]
    }
}
```

**Comment by haiyanghe** [comment]
Are there any solutions to this problem?

**Comment by akansal1** [comment]
Hi @100pah 

Any update on the issue discussed above ?

**Comment by c-okelly** [comment]
@100pah @haiyanghe @c-okelly I have a similar issues when using bar graph and time values for the xAxis. Using boundary gap does fix the issues when the chart is loaded but once you zoom in the issues appears again. Also using boundary gap wouldn't really take into account how different data might be displayed and would have to be adjusted for different data sets.

I am happy to work on the issue on the eCharts repo if I could get a bit of direction on it?

**Comment by c-okelly** [comment]
@100pah @haiyanghe I have implemented a proposed fix in a fork I have created at https://github.com/c-okelly/echarts. My idea is to make the chart start slightly earlier and finished slightly later when the presence of bars on a time graph is detected. 

The following code is added to axisHelper.js

`numberBarPlots = model.getModel().ecModel.getSeriesByType("bar").length;
        if (scaleType == 'time' && numberBarPlots > 0){
            var buffer = (max - min) * (0.01 * numberBarPlots);
            max += buffer;
            min -= buffer;
        }`

While the seems to fix the use case of as described above the issues reappears when the chart is zoomed in as show in the pictures below. No 1. No 2.

I have spend a good bit of time going over your code and trying to get to grips with the overall architecture you are using.

I would propose make the bug fix more intelligent first calculating to see if an overflow exists and then adjusting the start and end point of the xAxis to account for this (should ensure that the bars are within the Axis).

I am currently trying to understand how to calculate the box that would exist around each point on the graph. Red box in No 3.

I would very much appreciate any feedback you could provide or guidance on how I could adjust my fix to better fit in with your own overall plan. Or if you have a better idea to approach this problem.

Thanks,

Conor

No 1.
![screen shot 2017-09-13 at 18 03 10](https://user-images.githubusercontent.com/8889083/30390583-7e3f0ddc-98ae-11e7-9671-0edfe49498fc.png)

No 2.
![screen shot 2017-09-13 at 18 03 32](https://user-images.githubusercontent.com/8889083/30390607-91198482-98ae-11e7-9fba-57c59aae785f.png)


No 3.
![screen shot 2017-09-13 at 18 03 32](https://user-images.githubusercontent.com/8889083/30390651-bd5d29a4-98ae-11e7-8261-57f3e722e6d9.png)

**Comment by c-okelly** [comment]
I have opened a pull request that fixes this issues and works for zooming as well. #6728

**Comment by c-okelly** [comment]
@100pah Can we please close the issue.

Thanks,

C

**Comment by liujiong1982** [comment]
is this issue fixed?I am still seeing it in 3.3.4

**Comment by c-okelly** [comment]
@liujiong1982 This bug has been fixed in echarts version 4.0.3

**Comment by woakas** [comment]
Version 4.2.1 the issue persists

**Comment by c-okelly** [comment]
Issue does not persists it was fixed. This is a regression due to lack of testing for the use case.

Looking at the original fix and reworking it would be a reasonable starting point for someone looking to fix it

**Comment by c-okelly** [comment]
This issue is neither stale or closed.

This is a regression on a previous fix.

Could we please re-open this and I will try do the fix when I have some free time

**Comment by Terracotta45** [comment]
echarts@4.7.0 issue still persists. Since it's been almost 4 years since this issue was first reported and over 1 year since the last request to reopen, I'd be creating a new issue.

**Comment by ciesielskico** [comment]
Still an issue

**Comment by Ovilia** [comment]
Please follow #15671 for updates.
