### ISSUE TITLE
Cannot read property 'getRawIndex' of undefined

### ISSUE THREAD

**Issue by lolivia** [apache/incubator-echarts#9402]
### One-line summary [问题简述]

饼图未完全渲染，即饼图动态变化时，鼠标hover到饼图的扇区，报错Cannot read property 'getRawIndex' of undefined， 但不影响渲染以及后续使用

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  4.1.0
+ Browser version [浏览器类型和版本]: 70.0.3538.77
+ OS Version [操作系统类型和版本]: mac

### Expected behaviour [期望结果]

不输出该错误

### ECharts option [ECharts配置项]

```javascript
option = {
   tooltip: {
      show: true,
      formatter: (params) => {....},
  }
  series: [{
     name: '计数',
      type: 'pie',
      center: ['50%', '50%'],
      data: [{
       .......
       }]
   }]
  }
}

```
比较特殊的是 我的数据是远程获取，并且数据比较大，当整个饼图渲染完，并没有变化的时候，鼠标hover上去不会有什么错误，但是当数据还在加载的时候，饼图还在变化，这个时候鼠标hover上去会报错。
错误如下

### Other comments [其他信息]

dataFormat.js?6c1b:40 Uncaught TypeError: Cannot read property 'getRawIndex' of undefined
    at ExtendedClass.getDataParams (dataFormat.js?6c1b:40)
    at Function.superCall (clazz.js?04d6:107)
    at ExtendedClass.getDataParams (PieSeries.js?fef3:78)
    at ECharts.eval (echarts.js?21c7:1386)
    at Handler.trigger (Eventful.js?aa3b:158)
    at Handler.dispatchToElement (Handler.js?963e:218)
    at Handler.mouseout (Handler.js?963e:135)
    at HandlerDomProxy.trigger (Eventful.js?aa3b:158)
    at HandlerDomProxy.mouseout (HandlerProxy.js?7bcf:107)
    at HTMLDivElement.eval (HandlerProxy.js?7bcf:245)
getDataParams @ dataFormat.js?6c1b:40
superCall @ clazz.js?04d6:107
getDataParams @ PieSeries.js?fef3:78
(anonymous) @ echarts.js?21c7:1386
trigger @ Eventful.js?aa3b:158
dispatchToElement @ Handler.js?963e:218
mouseout @ Handler.js?963e:135
trigger @ Eventful.js?aa3b:158
mouseout @ HandlerProxy.js?7bcf:107
(anonymous) @ HandlerProxy.js?7bcf:245

**Comment by Ovilia** [comment]
Please provide a full example at jsfiddle or http://gallery.echartsjs.com/editor.html .
I tried to add `animationDuration: 5000` to slow down the animation and hover on pie before the animation completed and cannot reproduce it.

**Comment by lolivia** [comment]
不好意思 ，我们的场景比较复杂，不太好描述，如果单纯的写options，也确实不会出现这种问题，我想问下，因为我看到代码出错的地方是  var data = this.getData(dataType);这里为undefined，不知道是不是我姿势用的不对， 什么情况下 这里会undefined呢
![image](https://user-images.githubusercontent.com/6219377/48557626-37da1880-e922-11e8-825a-90698854504d.png)

**Comment by Ovilia** [comment]
I cannot tell from the provided information.
Please debug by yourself with ECharts repo `node build/build.js`.

**Comment by Ovilia** [comment]
@Pavel-Ropakov Can you provide your option?

**Comment by lixueying** [comment]
same for me

**Comment by braco** [comment]
Getting this also, not sure what the problem is.

**Comment by j4dream** [comment]
same for me

**Comment by CXX1431** [comment]
> 不好意思 ，我们的场景比较复杂，不太好描述，如果单纯的写options，也确实不会出现这种问题，我想问下，因为我看到代码出错的地方是 var data = this.getData(dataType);这里为undefined，不知道是不是我姿势用的不对， 一般什么情况下 这里会undefined呢
> ![image](https://user-images.githubusercontent.com/6219377/48557626-37da1880-e922-11e8-825a-90698854504d.png)

请问这个问题你们解决了么？

**Comment by wustdjf** [comment]
same for me

**Comment by xushimin** [comment]
same for me

**Comment by xushimin** [comment]
![image](https://user-images.githubusercontent.com/14247567/63777022-02cd0e80-c915-11e9-9b13-ee9f051868ab.png)
e.target.dataType 为undefined

**Comment by ankushjamdagani** [comment]
Same thing happening for us too. I have debugged it to this function. Task appears to be null here. And this function is returning undefined.

**Series.js**
```
  getData: function (dataType) {
    var task = getCurrentTask(this);

    if (task) {
      var data = task.context.data;
      return dataType == null ? data : data.getLinkedData(dataType);
    } else {
      // When series is not alive (that may happen when click toolbox
      // restore or setOption with not merge mode), series data may
      // be still need to judge animation or something when graphic
      // elements want to know whether fade out.
      return inner(this).data;
    }
  }
```

**Comment by Ovilia** [comment]
Anyone could provide a demo for this issue?

**Comment by hujinbo** [comment]
same for me

**Comment by anachronin** [comment]
I use `ReactEcharts` and had similar problem with 'scatter' and 'bar' series. Likely because events are being dispatched while the chart is re-rendering. After setting `silent: false` to the series, the error was eliminated. But this disabled `tooltip` too. 

The solution that works for me: use a React `shouldComponentUpdate` method to prevent Echarts from re-rendering.

**Comment by eslambasher** [comment]
I have the same error and the error disappeared when i deleted lazyUpdate from options

**Comment by hongdeyuan** [comment]
```
animationDuration: 5000,
animationDurationUpdate: 5000,
```

**Comment by hongdeyuan** [comment]
set :  silent: true , maybe it work

**Comment by a1292999652** [comment]
setOption<Opt extends ECBasicOption>(option: Opt, notMerge?: boolean, lazyUpdate?: boolean): void;
I passed "notMerge" into "true", this problem occurred, changed to "false", the problem was solved

**Comment by wayward-man** [comment]
> setOption(option: Opt, notMerge?: boolean, lazyUpdate?: boolean): void; I passed "notMerge" into "true", this problem occurred, changed to "false", the problem was solved

Yes，man. I solved the problem with the same way

**Comment by ggbond2077** [comment]
> 
+1 , i change state in select event which may cause render. caught the same error.  and the select action not work.  
solved by change "notMerge" to "false".

**Comment by ggbond2077** [comment]
> setOption(option: Opt, notMerge?: boolean, lazyUpdate?: boolean): void; I passed "notMerge" into "true", this problem occurred, changed to "false", the problem was solved

+1 , i change state in select event which may cause render. caught the same error. and the select action not work.
solved by change "notMerge" to "false".

**Comment by Forever17s** [comment]
> setOption(option: Opt, notMerge?: boolean, lazyUpdate?: boolean): void; I passed "notMerge" into "true", this problem occurred, changed to "false", the problem was solved

I set 'false' but it still doesn't work well. When switching to 'hover', the data still reports an error
![image](https://user-images.githubusercontent.com/35524901/231928478-b9fa764f-be75-4a55-8550-852cd0464fb1.png)

**Comment by ssjtbcf** [comment]
but If data is frequently changed,   change "notMerge"  into "false" is reasonable?

**Comment by hongdeyuan** [comment]
I have received your email, thank you!If there is anything important, I will reply to you as soon as I see it...

**Comment by lixueying** [comment]
已收到~
