### ISSUE TITLE
minShowLabelAngle无法生效

### ISSUE THREAD

**Issue by segmafrontend** [apache/incubator-echarts#9987]
### Version
4.2.1-rc1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xDMZGPdzFA&comment=0](https://gallery.echartsjs.com/editor.html?c=xDMZGPdzFA&comment=0)

### Steps to reproduce
无论在series还是在label中配置minShowLabelAngle均无效

### What is expected?
生效，work

### What is actually happening?
不起作用，do not work

**Comment by Ovilia** [comment]
Cannot reproduce in [current master](https://github.com/apache/incubator-echarts/commit/3c19eb3e8a6ad2c74d7b0e1e2b4c9db5ccc1fc8d). Probably fixed in https://github.com/apache/incubator-echarts/commit/b31e6d36b8e68b6d6af5d895536e52ba51417bdc .

**Comment by XiaoweiLiu19980812** [comment]
The link in reproduction link still don't work. Why close this issue?

**Comment by Ovilia** [comment]
@XiaoweiLiu19980812

**Comment by Ovilia** [comment]
Seem to still have bug. Reopen. Sorry.

**Comment by XiaoweiLiu0812** [comment]
@Ovilia  thank you very much~

**Comment by Ovilia** [comment]
Checked with the [latest master code](b6ab21159617b45c8077d998d468977cdd87d146) and this problem has been fixed. Please wait for next release.

**Comment by qcasxy** [comment]
> Checked with the [latest master code](b6ab21159617b45c8077d998d468977cdd87d146) and this problem has been fixed. Please wait for next release.

请问新的版本大概什么时候能够发布上线， 我现在也遇到了同样的问题。

**Comment by liuzirui1122** [comment]
> > Checked with the [latest master code](b6ab21159617b45c8077d998d468977cdd87d146) and this problem has been fixed. Please wait for next release.
> 
> 请问新的版本大概什么时候能够发布上线， 我现在也遇到了同样的问题。

目前可以通过对于百分比小于阈值的设置label show:false 暂时救急

**Comment by zdd2018** [comment]
> > > Checked with the [latest master code](b6ab21159617b45c8077d998d468977cdd87d146) and this problem has been fixed. Please wait for next release.
> > 
> > 
> > 请问新的版本大概什么时候能够发布上线， 我现在也遇到了同样的问题。
> 
> 目前可以通过对于百分比小于阈值的设置label show:false 暂时救急

具体怎么设置啊

**Comment by liuzirui1122** [comment]
> 具体怎么设置啊
[给你写了个demo
](https://gallery.echartsjs.com/editor.html?c=xwbbjasnr1&v=1)

**Comment by liuzirui1122** [comment]
@zdd2018 
[给你写了个demo](https://gallery.echartsjs.com/editor.html?c=xwbbjasnr1&v=1 )

**Comment by zdd2018** [comment]
> @ zdd2018 
> [给你写了个演示](https://gallery.echartsjs.com/editor.html?c=xwbbjasnr1&v=1)

3Q

**Comment by elephantme** [comment]
这个问题在4.3.0-rc.2已经修复了
